spring:
  application:
    name: market-data-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bitbuddy}
    username: ${DATASOURCE_USERNAME:bitbuddy}
    password: ${DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop   # oder validate/create-drop je nach Bedarf
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: market_data
  flyway:
    enabled: true
    schemas: market_data
    default-schema: market_data
    baseline-on-migrate: true
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

mds:
  provider: krakenMarketDataStreamingService
  crypto:
    pairs:
      - BTC/USD
      - ETH/USD
      - ADA/USD

logging:
  level:
    info.bitrich.xchangestream.bitstamp.v2.BitstampStreamingService: ERROR