server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketdata      # kann auch orderdecision/orderexecution
    username: market
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: public
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: viewer-api
      auto-offset-reset: latest

viewer:
  kafka:
    marketDataTopic: market-data-topic
  cors:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:3000
