replicaCount: 1

image:
  repository: docker.io/franjofranjic
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  auth:
    postgresPassword: admin1234
    username: orderdecision
    password: secret
    database: order_decision

datasource:
  username: orderdecision
  password: secret
  url: jdbc:postgresql://order-decision-service-postgresql:5432/order_decision

kafkaBootstrapServer: "bitbuddy-kafka:9092"

envFrom:
  - secretRef:
      name: order-decision-datasource-secret
  - configMapRef:
      name: kafka-config

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

# HPA
hpa:
  enabled: false

# PodDisruptionBudget
pdb:
  enabled: true
  minAvailable: 1
