apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: bitbuddy-dev
spec:
  ingressClassName: nginx
  rules:
    - host: argo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-argocd-server
                port:
                  number: 443
  tls:
    - hosts:
        - argo.local
      secretName: argocd-tls
