version: "3.9"

services:
  # --- Service 1: Market Data ---
  market-data-service:
    image: docker.io/franjofranjic/market-data-service:latest
    pull_policy: always
    container_name: market-data-service
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://market-data-db:5432/market_data
      - DATASOURCE_USERNAME=marketdata
      - DATASOURCE_PASSWORD=secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - market-data-db

  market-data-db:
    image: postgres:16
    container_name: market-data-db
    environment:
      - POSTGRES_DB=market_data
      - POSTGRES_USER=marketdata
      - POSTGRES_PASSWORD=secret
    ports:
      - "5433:5432"  # extern erreichbar für Debug

  # --- Service 2: Trade Decision ---
  order-decision-service:
    image: docker.io/franjofranjic/order-decision-service:latest
    pull_policy: always
    container_name: trade-decision-service
    ports:
      - "8082:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://order-decision-db:5432/order_decision
      - DATASOURCE_USERNAME=orderdecision
      - DATASOURCE_PASSWORD=secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - order-decision-db

  order-decision-db:
    image: postgres:16
    container_name: order-decision-db
    environment:
      - POSTGRES_DB=order_decision
      - POSTGRES_USER=orderdecision
      - POSTGRES_PASSWORD=secret
    ports:
      - "5434:5432"

  # --- Service 3: Order Execution ---
  order-execution-service:
    image: docker.io/franjofranjic/order-execution-service
    pull_policy: always
    container_name: order-execution-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-execution-db:5432/order_execution
      - SPRING_DATASOURCE_USERNAME=orderexecution
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - order-execution-db

  order-execution-db:
    image: postgres:16
    container_name: order-execution-db
    environment:
      - POSTGRES_DB=order_execution
      - POSTGRES_USER=execution
      - POSTGRES_PASSWORD=secret
    ports:
      - "5435:5432"

  # --- Kafka ---
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
