spring:
  application:
    name: order-decision-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_decision}
    username: ${DATASOURCE_USERNAME:orderdecision}
    password: ${DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop   # oder validate/create-drop je nach Bedarf
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: latest
      group-id: order-decision-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ch.ost.clde.dto"   # dein common DTO-Package

server:
  port: 8081
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always