AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Control Plane (ohne Node Group) – Kubernetes 1.29

Parameters:
  ClusterName:
    Type: String
    Default: bitbuddy
  KubernetesVersion:
    Type: String
    AllowedValues: [ '1.29', '1.28', '1.27' ]
    Default: '1.29'
  ClusterRoleArn:
    Type: String
    Description: ARN der LabEksClusterRole (aus IAM kopieren)

Resources:
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !Ref ClusterRoleArn
      ResourcesVpcConfig:
        SubnetIds:
          - !ImportValue bitbuddy-privateSubnetA
          - !ImportValue bitbuddy-privateSubnetB
        SecurityGroupIds:
          - !ImportValue bitbuddy-eks-sg
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
      KubernetesNetworkConfig:
        IpFamily: ipv4

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Path: /
      Tags:
        - Key: Name
          Value: bitbuddy-node-role

  EksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EksCluster
      NodegroupName: bitbuddy-nodes
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets:
        - !ImportValue bitbuddy-PrivateSubnetA
        - !ImportValue bitbuddy-PrivateSubnetB
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 4
      DiskSize: 20
      InstanceTypes:
        - t3.medium
      AmiType: AL2_x86_64

Outputs:
  ClusterName:
    Value: !Ref ClusterName
  ClusterArn:
    Value: !GetAtt EksCluster.Arn
  ClusterEndpoint:
    Value: !GetAtt EksCluster.Endpoint
  ClusterCertificateAuthorityData:
    Value: !GetAtt EksCluster.CertificateAuthorityData