AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL (bitbuddy) + Auto-Init (3 Schemas) via EC2 Runner

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0e86e20dae9224db8  # Amazon Linux 2

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: bitbuddy isolated subnet group
      SubnetIds:
        - !ImportValue bitbuddy-IsolatedSubnetA
        - !ImportValue bitbuddy-IsolatedSubnetB

  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: bitbuddy
      Engine: postgres
      EngineVersion: '16.3'
      DBName: bitbuddy
      MasterUsername: bitbuddy
      MasterUserPassword: secretsecret # needs to be at least 8 chars
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !ImportValue bitbuddy-rds-sg
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: false
      DeleteAutomatedBackups: true
      BackupRetentionPeriod: 0

Outputs:
  DBEndpoint:
    Value: !GetAtt PostgresDB.Endpoint.Address
  DBPort:
    Value: !GetAtt PostgresDB.Endpoint.Port
  DBNameOut:
    Value: bitbuddy