replicaCount: 1

image:
  repository: docker.io/franjofranjic
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  auth:
    postgresPassword: admin1234
    username: orderexecution
    password: secret
    database: order_execution

datasource:
  username: orderexecution
  password: secret
  url: jdbc:postgresql://order-execution-service-postgresql:5432/order_execution

kafka:
  enabled: false

envFrom:
  - secretRef:
      name: order-execution-service-datasource-secret

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

# HPA
hpa:
  enabled: false

# PodDisruptionBudget
pdb:
  enabled: true
  minAvailable: 1
