replicaCount: 2

image:
  repository: docker.io/franjofranjic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Route (nur für OpenShift)
route:
  enabled: true
  host: ""   # falls leer, wird automatisch generiert

# HPA
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# PodDisruptionBudget
pdb:
  enabled: true
  minAvailable: 1
