replicaCount: 1

image:
  repository: docker.io/franjofranjic
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  auth:
    postgresPassword: admin1234
    username: marketdata
    password: secret
    database: market_data

datasource:
  username: marketdata
  password: secret
  url: jdbc:postgresql://market-data-service-postgresql:5432/market_data

envFrom:
  - secretRef:
      name: market-data-service-datasource-secret
  - configMapRef:
      name: kafka-config

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080


# HPA
hpa:
  enabled: false

# PodDisruptionBudget
pdb:
  enabled: true
  minAvailable: 1
