name: helm verify

on:
  workflow_dispatch:

jobs:
  helm-verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ market-data-service, order-decision-service, order-execution-service ]
    name: Helm Verify (${{ matrix.service }})
    env:
      HELM_VERSION: v3.17.0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Lint Helm Chart
        run: helm lint helm/

      - name: Generate Template for Services
        run: helm template ${{ matrix.service }} helm/ -f ${{ matrix.service }}/helm/values.yml